version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
     - "30000:30000" 
  backend:
    build: ./node-backend/
    ports:
      - "3010:3010"
    volumes:
      - ./node-backend:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./react-frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/usr/src/app
    depends_on:
      - backend
